(async () => {
  await window.fixtureReady;
  const results = [];
  const assert = (name, condition) => {
    if (!condition) throw new Error(name);
    results.push(name);
  };
  const root = () => document.querySelector("#github-quick-preview")?.shadowRoot;
  const key = value => document.dispatchEvent(new KeyboardEvent("keydown", { key: value, bubbles: true, cancelable: true }));
  const click = (element, options = {}) => element.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true, button: 0, ...options }));
  const one = document.querySelector("#one");
  const two = document.querySelector("#two");
  const before = document.querySelector("#before");
  const source = one.currentSrc;
  const imagesBefore = performance.getEntriesByType("resource").filter(entry => entry.initiatorType === "img").length;
  window.scrollTo(0, 80);
  before.focus({ preventScroll: true });
  click(one);
  assert("Opens a modal and excludes badges, emoji, and collapsed screenshots", root().querySelector("dialog").open && root().querySelector(".count").textContent === "1 / 3");
  assert("Reuses the loaded image element and URL", root().querySelector(".stage img") === one && one.currentSrc === source);
  assert("Moves focus into the viewer", root().activeElement.getAttribute("aria-label") === "Close preview (Escape)");
  key("ArrowRight");
  assert("Right arrow follows before/after document order and restores the first image", root().querySelector(".stage img") === two && before.querySelector("img") === one);
  key("ArrowLeft");
  assert("Left arrow returns to the previous image", root().querySelector(".stage img") === one);
  root().querySelector("button[aria-pressed]").click();
  assert("Actual-size zoom works", root().querySelector(".stage").classList.contains("zoomed"));
  key("End");
  assert("Last image is bounded and resets zoom", root().querySelector(".count").textContent === "3 / 3" && !root().querySelector(".stage").classList.contains("zoomed") && root().querySelector("button[aria-label^='Next']").disabled);
  key("Escape");
  assert("Escape restores the image, focus, scroll, and scroll lock", !root() && before.querySelector("img") === one && document.activeElement === before && window.scrollY === 80 && !document.documentElement.style.overflow);
  assert("Previewing does not create image resource requests", performance.getEntriesByType("resource").filter(entry => entry.initiatorType === "img").length === imagesBefore);
  const modified = click(one, { metaKey: true });
  assert("Command-click keeps browser behavior", modified && !root());
  const added = one.cloneNode();
  added.id = "added";
  added.alt = "New comment screenshot";
  document.querySelector(".markdown-body").append(added);
  await added.decode();
  click(added);
  assert("Newly added comment images work without reinitializing", root().querySelector(".count").textContent === "4 / 4");
  document.dispatchEvent(new Event("turbo:before-render"));
  assert("GitHub navigation closes the viewer and restores the page", !root() && added.isConnected && !document.documentElement.style.overflow);
  history.replaceState({}, "", "/example/repository");
  const untouched = click(one);
  assert("Other GitHub pages keep ordinary clicks", untouched && !root());
  history.replaceState({}, "", "/example/repository/issues/2");
  click(one);
  assert("SPA navigation to an issue activates the viewer", !!root());
  key("Escape");
  return { passed: results.length, checks: results };
})();
