(async () => {
  await window.fixtureReady;
  const results = [];
  const assert = (name, condition) => {
    if (!condition) throw new Error(name);
    results.push(name);
  };
  const root = () => document.querySelector("#github-quick-preview")?.shadowRoot;
  const key = value => document.dispatchEvent(new KeyboardEvent("keydown", { key: value, bubbles: true, cancelable: true }));
  const click = (element, options = {}) => {
    let allowed = false;
    const preventNavigation = event => {
      allowed = !event.defaultPrevented;
      event.preventDefault();
    };
    element.addEventListener("click", preventNavigation);
    element.dispatchEvent(new MouseEvent("click", { bubbles: true, cancelable: true, button: 0, ...options }));
    element.removeEventListener("click", preventNavigation);
    return allowed;
  };
  const imageRequests = async () => {
    const response = await fetch("/__image_requests", { cache: "no-store" });
    if (!response.ok) throw new Error("Run the fixture with python3 scripts/test-server.py");
    return response.json();
  };
  const one = document.querySelector("#one");
  const two = document.querySelector("#two");
  const before = document.querySelector("#before");
  const source = one.currentSrc;
  const imagesBefore = await imageRequests();
  assert("The network check observes real HTTP fixture images", imagesBefore.some(path => path === "/tests/images/before.svg"));
  window.scrollTo(0, 80);
  before.focus({ preventScroll: true });
  click(one);
  assert("Opens a modal and excludes badges, emoji, and collapsed screenshots", root().querySelector("dialog").open && root().querySelector(".count").textContent === "1 / 3");
  assert("Reuses the loaded image element and URL", root().querySelector(".stage img") === one && one.currentSrc === source);
  const fitRect = one.getBoundingClientRect();
  const stage = root().querySelector(".stage");
  assert("Fit mode keeps the image within the available stage", fitRect.width <= stage.clientWidth + 1 && fitRect.height <= stage.clientHeight + 1);
  assert("Moves focus into the viewer", root().activeElement.getAttribute("aria-label") === "Close preview (Escape)");
  key("ArrowRight");
  assert("Right arrow follows before/after document order and restores the first image", root().querySelector(".stage img") === two && before.querySelector("img") === one);
  key("ArrowLeft");
  assert("Left arrow returns to the previous image", root().querySelector(".stage img") === one);
  root().querySelector("button[aria-pressed]").click();
  const zoomRect = one.getBoundingClientRect();
  assert("Actual-size zoom renders the image at its intrinsic dimensions", root().querySelector(".stage").classList.contains("zoomed") && Math.abs(zoomRect.width - one.naturalWidth) < 1 && Math.abs(zoomRect.height - one.naturalHeight) < 1);
  key("End");
  assert("Last image is bounded and resets zoom", root().querySelector(".count").textContent === "3 / 3" && !root().querySelector(".stage").classList.contains("zoomed") && root().querySelector("button[aria-label^='Next']").disabled);
  key("Escape");
  assert("Escape restores the image, focus, scroll, and scroll lock", !root() && before.querySelector("img") === one && document.activeElement === before && window.scrollY === 80 && !document.documentElement.style.overflow);
  await new Promise(resolve => setTimeout(resolve, 100));
  assert("Previewing does not start new HTTP image requests", (await imageRequests()).length === imagesBefore.length);
  const modified = click(one, { metaKey: true });
  assert("Command-click keeps browser behavior", modified && !root());
  assert("Keyboard activation of image-only links opens the viewer", !click(before) && !!root());
  key("Escape");
  const added = one.cloneNode();
  added.id = "added";
  added.alt = "New comment screenshot";
  document.querySelector(".markdown-body").append(added);
  await added.decode();
  click(added);
  assert("Newly added comment images work without reinitializing", root().querySelector(".count").textContent === "4 / 4");
  document.dispatchEvent(new Event("turbo:before-render"));
  assert("GitHub navigation closes the viewer and restores the page", !root() && added.isConnected && !document.documentElement.style.overflow);
  history.replaceState({}, "", "/example/repository");
  const untouched = click(one);
  assert("Other GitHub pages keep ordinary clicks", untouched && !root());
  history.replaceState({}, "", "/example/repository/issues/2");
  click(one);
  assert("SPA navigation to an issue activates the viewer", !!root());
  key("Escape");
  const overflow = document.documentElement.style;
  overflow.setProperty("overflow-x", "hidden", "important");
  click(one);
  key("Escape");
  assert("Closing restores an individual overflow axis and its priority", overflow.getPropertyValue("overflow-x") === "hidden" && overflow.getPropertyPriority("overflow-x") === "important" && overflow.getPropertyValue("overflow-y") === "");
  overflow.setProperty("overflow-y", "scroll");
  click(one);
  key("Escape");
  assert("Closing restores overflow axes with different priorities", overflow.getPropertyValue("overflow-x") === "hidden" && overflow.getPropertyPriority("overflow-x") === "important" && overflow.getPropertyValue("overflow-y") === "scroll" && overflow.getPropertyPriority("overflow-y") === "");
  overflow.removeProperty("overflow-x");
  overflow.removeProperty("overflow-y");
  const label = document.createElement("span");
  label.textContent = "Read details";
  before.append(label);
  assert("Text links beside images keep ordinary navigation", click(label) && !root());
  label.remove();
  const broken = document.createElement("img");
  broken.width = 100;
  broken.height = 20;
  broken.alt = "Broken badge";
  const failed = new Promise(resolve => broken.addEventListener("error", resolve, { once: true }));
  broken.src = "/tests/images/missing-badge.svg";
  document.querySelector(".markdown-body").append(broken);
  await failed;
  click(one);
  assert("Broken badges are excluded from the gallery", root().querySelector(".count").textContent === "1 / 4");
  key("Escape");
  broken.remove();
  const pending = document.createElement("img");
  pending.loading = "lazy";
  pending.width = 100;
  pending.height = 20;
  pending.alt = "Pending badge";
  pending.src = "/tests/images/badge.svg?pending";
  document.querySelector(".markdown-body").append(pending);
  assert("The pending badge starts without intrinsic dimensions", pending.naturalWidth === 0 && !pending.complete);
  click(one);
  assert("Pending small badges are excluded from the gallery", root().querySelector(".count").textContent === "1 / 4");
  key("Escape");
  pending.remove();
  const picture = document.createElement("picture");
  const pictureSource = document.createElement("source");
  pictureSource.srcset = "/tests/images/after.svg";
  const pictureImage = one.cloneNode();
  pictureImage.removeAttribute("id");
  picture.append(pictureSource, pictureImage);
  document.querySelector(".markdown-body").append(picture);
  await pictureImage.decode();
  const selectedSource = pictureImage.currentSrc;
  click(pictureImage);
  assert("Picture previews preserve the original picture and selected source", root().querySelector(".stage picture") === picture && pictureImage.currentSrc === selectedSource);
  key("Escape");
  assert("Closing restores the original picture and its source children", picture.parentElement.classList.contains("markdown-body") && picture.firstElementChild === pictureSource && pictureImage.parentElement === picture);
  picture.remove();
  return { passed: results.length, checks: results };
})();
